dist: bionic
language: python
python:
  - "3.7"
install:
  - pip install flake8 codecov black isort
  - pip install -e .[test]
script:
  - isort -c -rc guillotina_evolution
  - flake8 guillotina_evolution --config=setup.cfg
  - black guillotina_evolution --check
  - pytest --cov=guillotina_evolution -v --cov-report term-missing guillotina_evolution
after_success:
  - codecov
